name: 'Test spack recipes'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SOURCE_DIR_SPACK: '/__w/spack/src'

jobs:
  tests:
    name: 'Build and Test'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          ref: releases/v1.0
          path: spack

      - name: Print directory infos
        shell: 'bash'
        run: |
          ls -lart '${{ github.workspace }}'

      - name: Add ArcaneFramework repo
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack repo add .

      - name: Print ArcaneFramework spec
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack info arcane-framework
          spack spec arcane-framework
          spack info arcane

      - name: Print Arcane spec
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack info arcane
          spack spec arcane

      - name: Build package Arccore
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack install arcane-framework build_type=Debug ~arcane

      - name: Build package Arcane
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack install arcane-framework build_type=Debug +arcane

      - name: Build package Alien
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack install arcane-framework build_type=Debug ~arcane +alien

      - name: Build package Arcane and Alien
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack install arcane-framework build_type=Debug +arcane +alien
