name: 'Test spack recipes'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SOURCE_DIR_SPACK: '/__w/spack/src'

jobs:
  tests:
    name: 'Build and Test'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          ref: v0.22.1
          path: spack

      - name: Print directory infos
        shell: 'bash'
        run: |
          ls -lart '${{ github.workspace }}'

      - name: Check And build package Arcane
        shell: 'bash'
        run: |
          . spack/share/spack/setup-env.sh
          spack repo add .
          spack info arcane
          spack spec arcane
          spack install arcane build_type=Debug
